"""Round-5 acceptance reproductions for GitHub issue #1 (A-E prescription). Independent expected results
(hand-specified, NOT generated by the code under test). Each must FAIL on the pre-fix code and PASS after.
Gates are not weakened; unresolved is never treated as conformant."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'synthetic'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"'
TEMPLATE = os.path.join(os.path.dirname(__file__), '..', 'src', 'conformer', 'assets', 'template.dotx')


# =================================================================== A. NumberingGraph resolution
def test_a_heading_selects_linked_level_not_ilvl0():
    # Heading2's style numPr carries ONLY numId 1 (no ilvl). Instance 1 -> abstract 20, whose level 1 is
    # pStyle-linked to Heading2. Correct resolution selects instance 1 and the ASSOCIATED level 1 -> (1,1),
    # decimal '%1.%2'. The old explicit-numId early return yields (1,0) which does not resolve.
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="20">'
           '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1"/></w:lvl>'
           '<w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1.%2"/>'
           '<w:pStyle w:val="Heading2"/></w:lvl></w:abstractNum>'
           '<w:num w:numId="1"><w:abstractNumId w:val="20"/></w:num></w:numbering>')
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/>'
           '<w:pPr><w:numPr><w:numId w:val="1"/></w:numPr></w:pPr></w:style></w:styles>')
    g = NumberingGraph(num, sty)
    r = g.resolve_style('Heading2')
    assert r.state == 'resolved', r.reason
    assert (r.numId, r.ilvl) == ('1', '1'), (r.numId, r.ilvl)
    assert r.level['lvlText'] == '%1.%2'


def _two_instance_pkg(reverse=False):
    a = ('<w:abstractNum w:abstractNumId="20"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
         '<w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:pStyle w:val="H"/></w:lvl></w:abstractNum>')
    n1 = '<w:num w:numId="1"><w:abstractNumId w:val="20"/></w:num>'
    n9 = ('<w:num w:numId="9"><w:abstractNumId w:val="20"/>'
          '<w:lvlOverride w:ilvl="0"><w:startOverride w:val="9"/></w:lvlOverride></w:num>')
    nums = (n9 + n1) if reverse else (n1 + n9)
    num = f'<w:numbering {W}>{a}{nums}</w:numbering>'
    sty = f'<w:styles {W}><w:style w:type="paragraph" w:styleId="H"><w:name w:val="H"/></w:style></w:styles>'
    return num, sty


def test_a_ambiguous_instance_is_unresolved():
    # Style H has no numPr; abstract 20 is pStyle-linked to H; TWO instances (num 1 start 1, num 9 start 9)
    # reference abstract 20. There is no basis to pick one -> UNRESOLVED, never a silent first-instance win.
    from conformer.numbering import NumberingGraph
    num, sty = _two_instance_pkg(reverse=False)
    g = NumberingGraph(num, sty)
    r = g.resolve_style('H')
    assert r.state == 'unresolved', (r.state, r.numId, r.ilvl)


def test_a_definition_order_independent():
    # Reversing the XML order of the two instances must NOT change the result (both unresolved here).
    from conformer.numbering import NumberingGraph
    r1 = NumberingGraph(*_two_instance_pkg(reverse=False)).resolve_style('H')
    r2 = NumberingGraph(*_two_instance_pkg(reverse=True)).resolve_style('H')
    assert r1.state == r2.state
    assert (r1.numId, r1.ilvl) == (r2.numId, r2.ilvl)


def test_a_numid0_is_no_numbering_not_unresolved():
    from conformer.numbering import NumberingGraph
    num = f'<w:numbering {W}></w:numbering>'
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="X"><w:name w:val="X"/>'
           '<w:pPr><w:numPr><w:numId w:val="0"/></w:numPr></w:pPr></w:style></w:styles>')
    r = NumberingGraph(num, sty).resolve_style('X')
    assert r.state == 'none', r.state


def test_a_missing_instance_is_unresolved_not_none():
    from conformer.numbering import NumberingGraph
    num = f'<w:numbering {W}></w:numbering>'
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="X"><w:name w:val="X"/>'
           '<w:pPr><w:numPr><w:numId w:val="77"/></w:numPr></w:pPr></w:style></w:styles>')
    r = NumberingGraph(num, sty).resolve_style('X')
    assert r.state == 'unresolved', r.state


def test_a_partial_direct_ilvl_merges_with_inherited_instance():
    # A paragraph's direct numPr has an ilvl but NO numId; the numId comes from its style. The direct ilvl
    # must NOT be discarded: resolve to (style numId, direct ilvl).
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="30">'
           '<w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl>'
           '<w:lvl w:ilvl="1"><w:numFmt w:val="lowerLetter"/><w:lvlText w:val="%2)"/></w:lvl>'
           '</w:abstractNum><w:num w:numId="5"><w:abstractNumId w:val="30"/></w:num></w:numbering>')
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="L"><w:name w:val="L"/>'
           '<w:pPr><w:numPr><w:numId w:val="5"/></w:numPr></w:pPr></w:style></w:styles>')
    g = NumberingGraph(num, sty)
    r = g.resolve_paragraph(None, '1', 'L')          # direct ilvl 1, no direct numId
    assert r.state == 'resolved' and (r.numId, r.ilvl) == ('5', '1'), (r.state, r.numId, r.ilvl)
    assert r.level['numFmt'] == 'lowerLetter'


# =================================================================== B. Whole-instance repair
def _bconf(num, sty, tnum, tsty, items=None):
    from conformer.engine import Conformer
    c = Conformer.__new__(Conformer)
    c._skip = lambda k: False
    c.say = lambda *a, **k: None
    c._house_repaired = {}
    c._unresolved_imports = []
    c._table_notes = []
    c.num = num; c.styles = sty
    c._orig_num0 = num; c._orig_styles0 = sty
    c.t_num = tnum; c.t_styles = tsty
    c.items = list(items or []); c.b0 = 0
    c._orig_items0 = list(items or []); c._orig_b0 = 0
    return c


def _np2_styles(numsrc):
    return (f'<w:styles {W}>'
            '<w:style w:type="paragraph" w:styleId="NumberedParagraph"><w:name w:val="NumberedParagraph"/>'
            f'<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="{numsrc}"/></w:numPr></w:pPr></w:style>'
            '<w:style w:type="paragraph" w:styleId="NumberedParagraphL1"><w:name w:val="NumberedParagraphL1"/>'
            f'<w:pPr><w:numPr><w:ilvl w:val="1"/><w:numId w:val="{numsrc}"/></w:numPr></w:pPr></w:style>'
            '</w:styles>')


def test_b_partial_corruption_keeps_shared_instance():
    # numId 5 shared by NumberedParagraph (lvl0, BROKEN) and NumberedParagraphL1 (lvl1, ALREADY CORRECT).
    # Only lvl0 needs repair; the two styles must remain on ONE shared instance, not split.
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="50">'
           '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="BROKEN1"/></w:lvl>'
           '<w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1.%2."/></w:lvl>'
           '</w:abstractNum><w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num></w:numbering>')
    tnum = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="70">'
            '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl>'
            '<w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1.%2."/></w:lvl>'
            '</w:abstractNum><w:num w:numId="9"><w:abstractNumId w:val="70"/></w:num></w:numbering>')
    c = _bconf(num, _np2_styles('5'), tnum, _np2_styles('9'))
    c._repair_styles()
    g = NumberingGraph(c.num, c.styles)
    n0 = g.style_numpr('NumberedParagraph'); n1 = g.style_numpr('NumberedParagraphL1')
    assert n0 is not None and n1 is not None
    assert n0[0] == n1[0], f'partial repair split the shared instance: {n0} vs {n1}'
    assert g.resolve_level(*n0)['lvlText'] == '%1.'      # lvl0 label repaired
    assert g.resolve_level(*n1)['lvlText'] == '%1.%2.'   # lvl1 preserved


def test_b_healthy_direct_user_rebound_to_repaired_instance():
    # numId 5 used by style NumberedParagraph (lvl0, broken) AND a DIRECT paragraph reference (numId 5,
    # lvl 1, non-tracked). Repairing the instance must rebind the direct user to the SAME new instance.
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="50">'
           '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="BROKEN1"/></w:lvl>'
           '<w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1.%2."/></w:lvl>'
           '</w:abstractNum><w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num></w:numbering>')
    tnum = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="70">'
            '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl>'
            '<w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1.%2."/></w:lvl>'
            '</w:abstractNum><w:num w:numId="9"><w:abstractNumId w:val="70"/></w:num></w:numbering>')
    para = ('<w:p><w:pPr><w:numPr><w:ilvl w:val="1"/><w:numId w:val="5"/></w:numPr></w:pPr>'
            '<w:r><w:t>direct user</w:t></w:r></w:p>')
    c = _bconf(num, _np2_styles('5'), tnum, _np2_styles('9'), items=[para])
    c._repair_styles()
    g = NumberingGraph(c.num, c.styles)
    style_nid = g.style_numpr('NumberedParagraph')[0]
    import re as _re
    m = _re.search(r'<w:numId w:val="([^"]+)"', c.items[0])
    assert m and m.group(1) == style_nid, 'direct user not rebound to the repaired instance'


def test_b_independent_instances_sharing_abstract_stay_independent():
    from conformer.numbering import NumberingGraph
    # numId 5 and numId 6 both reference abstract 50; style A uses 5 (broken), style B uses 6 (independent).
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="50"><w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/>'
           '<w:lvlText w:val="BROKEN"/></w:lvl></w:abstractNum>'
           '<w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num>'
           '<w:num w:numId="6"><w:abstractNumId w:val="50"/></w:num></w:numbering>')

    def sty(a, b):
        return (f'<w:styles {W}>'
                '<w:style w:type="paragraph" w:styleId="ListNumber"><w:name w:val="ListNumber"/>'
                f'<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="{a}"/></w:numPr></w:pPr></w:style>'
                '<w:style w:type="paragraph" w:styleId="ListNumber2"><w:name w:val="ListNumber2"/>'
                f'<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="{b}"/></w:numPr></w:pPr></w:style></w:styles>')
    tnum = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="70"><w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/>'
            '<w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
            '<w:num w:numId="8"><w:abstractNumId w:val="70"/></w:num>'
            '<w:num w:numId="9"><w:abstractNumId w:val="70"/></w:num></w:numbering>')
    c = _bconf(num, sty('5', '6'), tnum, sty('8', '9'))
    c._repair_styles()
    g = NumberingGraph(c.num, c.styles)
    a = g.style_numpr('ListNumber')[0]; b = g.style_numpr('ListNumber2')[0]
    assert a != b, 'independent instances (5 vs 6) were merged'
    assert '6' == b or b != a   # B keeps its own instance


# =================================================================== C. Exact authorization
def _scan_conf(onum, osty, num, sty, oitems, items, repaired=None):
    from conformer.engine import Conformer
    c = Conformer.__new__(Conformer)
    c._orig_num0 = onum; c._orig_styles0 = osty
    c.num = num; c.styles = sty
    c._orig_items0 = list(oitems); c._orig_b0 = 0
    c.items = list(items); c.b0 = 0
    c._house_repaired = repaired or {}
    return c


_C_STYLES = (f'<w:styles {W}>'
             '<w:style w:type="paragraph" w:styleId="Decimal"><w:name w:val="Decimal"/>'
             '<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="5"/></w:numPr></w:pPr></w:style>'
             '<w:style w:type="paragraph" w:styleId="Bullet"><w:name w:val="Bullet"/>'
             '<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="6"/></w:numPr></w:pPr></w:style></w:styles>')
_C_NUM = (f'<w:numbering {W}>'
          '<w:abstractNum w:abstractNumId="50"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
          '<w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
          '<w:abstractNum w:abstractNumId="60"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
          '<w:numFmt w:val="bullet"/><w:lvlText w:val="o"/></w:lvl></w:abstractNum>'
          '<w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num>'
          '<w:num w:numId="6"><w:abstractNumId w:val="60"/></w:num></w:numbering>')


def _p(paraid, pstyle=None, numid=None, ilvl='0', text='item'):
    ppr = ''
    if pstyle:
        ppr += f'<w:pStyle w:val="{pstyle}"/>'
    if numid:
        ppr += f'<w:numPr><w:ilvl w:val="{ilvl}"/><w:numId w:val="{numid}"/></w:numPr>'
    ppr = f'<w:pPr>{ppr}</w:pPr>' if ppr else ''
    return f'<w:p w14:paraId="{paraid}">{ppr}<w:r><w:t>{text}</w:t></w:r></w:p>'


def test_c_pstyle_change_without_manifest_fails():
    before = [_p('AAAA', pstyle='Decimal')]
    after = [_p('AAAA', pstyle='Bullet')]                 # style changed Decimal -> Bullet, no repair
    c = _scan_conf(_C_NUM, _C_STYLES, _C_NUM, _C_STYLES, before, after)
    assert c._paragraph_reference_scan()['flips'], 'unauthorized pStyle numbering change not caught'


def test_c_dropping_functioning_direct_decimal_over_bullet_style_fails():
    before = [_p('BBBB', pstyle='Bullet', numid='5')]     # functioning direct decimal on a bullet style
    after = [_p('BBBB', pstyle='Bullet')]                 # direct numbering dropped -> becomes bullets
    c = _scan_conf(_C_NUM, _C_STYLES, _C_NUM, _C_STYLES, before, after)
    assert c._paragraph_reference_scan()['flips'], 'dropping a functioning direct decimal not caught'


def test_c_same_format_instance_swap_changes_continuation_fails():
    # two instances, identical LEVEL PROPERTIES but different instances (independent counters). Swapping a
    # paragraph from one to the other changes continuation and must fail even though numFmt/lvlText match.
    num = (f'<w:numbering {W}>'
           '<w:abstractNum w:abstractNumId="50"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
           '<w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
           '<w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num>'
           '<w:num w:numId="9"><w:abstractNumId w:val="50"/></w:num></w:numbering>')
    sty = f'<w:styles {W}></w:styles>'
    before = [_p('CCCC', numid='5')]
    after = [_p('CCCC', numid='9')]
    c = _scan_conf(num, sty, num, sty, before, after)
    assert c._paragraph_reference_scan()['flips'], 'same-format instance swap (continuation change) not caught'


def _repair_pkg():
    onum = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="50"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
            '<w:numFmt w:val="decimal"/><w:lvlText w:val="BROKEN"/></w:lvl></w:abstractNum>'
            '<w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num></w:numbering>')
    osty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="ListX"><w:name w:val="ListX"/>'
            '<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="5"/></w:numPr></w:pPr></w:style></w:styles>')
    return onum, osty


def test_c_valid_label_repair_passes():
    onum, osty = _repair_pkg()
    num = onum.replace('</w:numbering>',
                       '<w:abstractNum w:abstractNumId="60"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
                       '<w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
                       '<w:num w:numId="6"><w:abstractNumId w:val="60"/></w:num></w:numbering>')
    sty = osty.replace('<w:numId w:val="5"/>', '<w:numId w:val="6"/>')     # ListX rewired 5 -> 6 (label fixed)
    repaired = {'ListX': {'ilvl': '0', 'shared_new_numId': '6',
                          'before': {'numFmt': 'decimal', 'lvlText': 'BROKEN', 'start': '1', 'isLgl': False,
                                     'lvlRestart': None},
                          'after_expected': {'numFmt': 'decimal', 'lvlText': '%1.', 'start': '1',
                                             'isLgl': False, 'lvlRestart': None}}}
    before = [_p('DDDD', pstyle='ListX')]
    after = [_p('DDDD', pstyle='ListX')]
    c = _scan_conf(onum, osty, num, sty, before, after, repaired)
    assert c._paragraph_reference_scan()['flips'] == [], 'a valid recorded label repair must pass'


def test_c_repair_plus_start_alteration_fails():
    onum, osty = _repair_pkg()
    num = onum.replace('</w:numbering>',
                       '<w:abstractNum w:abstractNumId="60"><w:lvl w:ilvl="0"><w:start w:val="9"/>'   # start reset!
                       '<w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
                       '<w:num w:numId="6"><w:abstractNumId w:val="60"/></w:num></w:numbering>')
    sty = osty.replace('<w:numId w:val="5"/>', '<w:numId w:val="6"/>')
    repaired = {'ListX': {'ilvl': '0', 'shared_new_numId': '6',
                          'before': {'numFmt': 'decimal', 'lvlText': 'BROKEN', 'start': '1', 'isLgl': False,
                                     'lvlRestart': None},
                          'after_expected': {'numFmt': 'decimal', 'lvlText': '%1.', 'start': '1',   # expected start 1
                                             'isLgl': False, 'lvlRestart': None}}}
    before = [_p('EEEE', pstyle='ListX')]
    after = [_p('EEEE', pstyle='ListX')]
    c = _scan_conf(onum, osty, num, sty, before, after, repaired)
    assert c._paragraph_reference_scan()['flips'], 'a repair that also alters start must fail'


# =================================================================== D. Header background+foreground pair
_GRIDTABLE4_STYLE = (f'<w:styles {W}><w:style w:type="table" w:styleId="GridTable4"><w:name w:val="Grid Table 4"/>'
                     '<w:aliases w:val="LI Table"/><w:tblPr><w:tblBorders>'
                     + ''.join(f'<w:{s} w:val="single" w:sz="4" w:color="auto"/>'
                               for s in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'))
                     + '</w:tblBorders></w:tblPr>'
                     '<w:tblStylePr w:type="firstRow"><w:rPr><w:b/><w:color w:val="auto"/></w:rPr>'
                     '<w:tcPr><w:shd w:val="clear" w:fill="B6DDE8"/></w:tcPr></w:tblStylePr></w:style></w:styles>')


def _hdr_table(cell_shd='', run_rpr='', tbllook='<w:tblLook w:firstRow="1"/>'):
    return ('<w:tbl><w:tblPr><w:tblStyle w:val="GridTable4"/>' + tbllook + '</w:tblPr>'
            '<w:tblGrid><w:gridCol w:w="2000"/></w:tblGrid>'
            f'<w:tr><w:trPr><w:tblHeader/></w:trPr><w:tc><w:tcPr>{cell_shd}</w:tcPr>'
            f'<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr>{run_rpr}</w:rPr>'
            '<w:t>H</w:t></w:r></w:p></w:tc></w:tr></w:tbl>')


def test_d_white_header_fill_is_not_clean():
    from conformer.tablespec import effective_table_issues, table_conformant
    frag = _hdr_table(cell_shd='<w:shd w:val="clear" w:fill="FFFFFF"/>',
                      run_rpr='<w:color w:val="000000"/>')
    assert table_conformant(frag, styles_xml=_GRIDTABLE4_STYLE) is False   # white bg is not the teal header


def test_d_header_conditional_off_is_not_house():
    # firstRow conditional DISABLED (tblLook firstRow=0): the teal header formatting is not applied.
    from conformer.tablespec import effective_table_issues
    frag = _hdr_table(cell_shd='<w:shd w:val="clear" w:fill="B6DDE8"/>', run_rpr='<w:color w:val="auto"/>',
                      tbllook='<w:tblLook w:firstRow="0"/>')
    issues = effective_table_issues(frag, styles_xml=_GRIDTABLE4_STYLE)
    assert any(i['kind'] == 'header-conditional-off' for i in issues)


def test_d_accent5_theme_is_house_but_other_accent_fails():
    # the house header IS carried as themeFill accent5; a DIFFERENT accent (accent1) is not the house teal
    from conformer.tablespec import effective_table_issues
    accent5 = _hdr_table(cell_shd='<w:shd w:val="clear" w:themeFill="accent5" w:themeFillTint="66"/>',
                         run_rpr='<w:color w:val="auto"/>')
    assert not any(i['kind'] == 'header-fill' for i in effective_table_issues(accent5, styles_xml=_GRIDTABLE4_STYLE))
    accent1 = _hdr_table(cell_shd='<w:shd w:val="clear" w:themeFill="accent1"/>', run_rpr='<w:color w:val="auto"/>')
    assert any(i['kind'] == 'header-fill' for i in effective_table_issues(accent1, styles_xml=_GRIDTABLE4_STYLE))


def test_d_repair_normalizes_white_and_auto_and_theme_to_concrete_teal():
    from conformer.engine import Conformer
    c = Conformer.__new__(Conformer)
    c._table_notes = []
    for fill in ('FFFFFF', 'auto', 'theme'):
        shd = ('<w:shd w:val="clear" w:themeFill="accent1"/>' if fill == 'theme'
               else f'<w:shd w:val="clear" w:fill="{fill}"/>')
        row = (f'<w:tr><w:trPr><w:tblHeader/></w:trPr><w:tc><w:tcPr>{shd}</w:tcPr>'
               '<w:p><w:r><w:t>H</w:t></w:r></w:p></w:tc></w:tr>')
        out, rep, _ = c._repair_stray_header_formatting(f'<w:tbl>{row}</w:tbl>', 'T')
        assert 'w:fill="B6DDE8"' in out, (fill, out)
        assert 'themeFill' not in out and 'FFFFFF' not in out, (fill, out)


def test_d_tracked_current_header_fill_corrected_history_byte_identical():
    from conformer.engine import Conformer
    c = Conformer.__new__(Conformer)
    c._table_notes = []
    change = '<w:tcPrChange w:id="7" w:author="R"><w:tcPr><w:shd w:val="clear" w:fill="ABCDEF"/></w:tcPr></w:tcPrChange>'
    row = ('<w:tr><w:trPr><w:tblHeader/></w:trPr>'
           f'<w:tc><w:tcPr><w:shd w:val="clear" w:fill="D9EAF7"/>{change}</w:tcPr>'
           '<w:p><w:r><w:t>H</w:t></w:r></w:p></w:tc></w:tr>')
    out, rep, tracked = c._repair_stray_header_formatting(f'<w:tbl>{row}</w:tbl>', 'T')
    assert 'w:fill="B6DDE8"' in out and 'D9EAF7' not in out        # current fill -> concrete teal
    assert change in out                                          # tracked-change snapshot byte-identical


# =================================================================== E. Truthful saving
def _save_conf(status_fn):
    from conformer.engine import Conformer
    c = Conformer.__new__(Conformer)
    c._save_verdict = 'unset'; c._save_gen = -1; c._gen = 0; c._save_forced_review = False
    c.disposition = None
    c.conformance_status = status_fn
    return c


def test_e_finalize_save_requires_review_only_for_nonclean():
    import pytest
    from conformer.engine import ReviewOnlyRequired
    c = _save_conf(lambda: {'clean': False, 'blocking': True, 'reasons': {}})
    with pytest.raises(ReviewOnlyRequired):
        c.finalize_save(review_only=False)
    v = c.finalize_save(review_only=True)              # explicit opt-in proceeds
    assert v['blocking'] is True and c._save_forced_review is True


def test_e_finalize_save_clean_needs_no_optin():
    c = _save_conf(lambda: {'clean': True, 'blocking': False, 'reasons': {}})
    v = c.finalize_save(review_only=False)             # clean -> no permission needed
    assert v['clean'] is True and c._save_forced_review is False


def test_e_verifier_exception_is_unknown_not_clean():
    def boom():
        raise RuntimeError('verifier boom')
    c = _save_conf(boom)
    v = c._finalize_verdict(force=True)
    assert v is None and c._save_forced_review is True
    assert 'UNVERIFIED' in c._artifact_label(v, True).upper()


def test_e_edit_invalidates_finalized_verdict():
    c = _save_conf(lambda: {'clean': True, 'blocking': False, 'reasons': {}})
    assert c._finalize_verdict()['clean'] is True and c._save_gen == 0
    c.conformance_status = lambda: {'clean': False, 'blocking': True, 'reasons': {}}
    c._gen = 1                                          # a later edit bumps the generation
    assert c._finalize_verdict()['clean'] is False      # stale verdict recomputed


def test_e_review_only_output_is_distinct_even_in_replace_mode():
    import os as _os, tempfile
    _os.environ['QT_QPA_PLATFORM'] = 'offscreen'
    from PySide6.QtWidgets import QApplication
    QApplication.instance() or QApplication([])
    from conformer.ui.window import MainWindow
    mw = MainWindow.__new__(MainWindow)
    src = _os.path.join(tempfile.mkdtemp(), 'orig.docx')
    open(src, 'wb').write(b'PK-source')
    mw.input_path = src
    mw.output_mode = 'replace'                          # replace mode...
    mw._chosen_output = None

    class _F:
        _save_forced_review = True                     # ...but the copy is UNVERIFIED
        disposition = None
        log = []; judgment = []; audit = []
        def save(self, p): _F.saved = p
        def write_audit(self, p): _F.audit_path = p
    f = _F()
    out = mw._save_output(f)
    assert out != src and 'REVIEW COPY - UNVERIFIED' in out   # never overwrote the source
    assert getattr(_F, 'saved', None) == out
    assert getattr(_F, 'audit_path', None) == out            # audit written (failure would propagate)


# =================================================================== numbering.xml schema order (Word oracle)
def test_imported_definitions_keep_abstractnums_before_nums():
    # CRITICAL: a repair that imports new numbering definitions must keep EVERY <w:abstractNum> before
    # EVERY <w:num> in numbering.xml (CT_Numbering order). If they interleave Word drops ALL numbering,
    # even though the XML is well-formed and the resolver (order-blind) sees numbering fine.
    import re as _re
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="50">'
           '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="BROKEN"/></w:lvl>'
           '</w:abstractNum><w:num w:numId="5"><w:abstractNumId w:val="50"/></w:num></w:numbering>')
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="NumberedParagraph">'
           '<w:name w:val="NumberedParagraph"/><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="5"/>'
           '</w:numPr></w:pPr></w:style></w:styles>')
    tnum = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="70">'
            '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl>'
            '</w:abstractNum><w:num w:numId="9"><w:abstractNumId w:val="70"/></w:num></w:numbering>')
    tsty = sty.replace('w:numId w:val="5"', 'w:numId w:val="9"')
    c = _bconf(num, sty, tnum, tsty)
    c._repair_styles()
    out = c.num
    assert '<w:num w:numId=' in out and '<w:abstractNum ' in out
    abs_last = max(m.start() for m in _re.finditer(r'<w:abstractNum\b', out))
    num_first = min(m.start() for m in _re.finditer(r'<w:num\b(?![a-zA-Z])', out))
    assert abs_last < num_first, 'imported <w:abstractNum> ended up AFTER a <w:num> (Word drops all numbering)'
    # and every num still resolves (no dangling references)
    g = NumberingGraph(out, c.styles)
    assert g.resolve_style('NumberedParagraph').resolved


# =================================================================== dysfunctional bullet restore (Claire)
def test_restore_suppressed_bullet_on_house_bullet_style():
    # A paragraph styled as a house bullet (ListBullet) whose bullet is cancelled by an explicit numId=0
    # is restored (the numId=0 override removed) so the style's bullet renders. NumberedParagraph (a
    # NUMBER style) with numId=0 is NOT touched (that may be an intentional un-numbered continuation).
    from conformer.engine import Conformer
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="40"><w:lvl w:ilvl="0">'
           '<w:numFmt w:val="bullet"/><w:lvlText w:val="o"/></w:lvl></w:abstractNum>'
           '<w:abstractNum w:abstractNumId="41"><w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/>'
           '<w:lvlText w:val="%1."/></w:lvl></w:abstractNum>'
           '<w:num w:numId="7"><w:abstractNumId w:val="40"/></w:num>'
           '<w:num w:numId="8"><w:abstractNumId w:val="41"/></w:num></w:numbering>')
    sty = (f'<w:styles {W}>'
           '<w:style w:type="paragraph" w:styleId="ListBullet"><w:name w:val="ListBullet"/>'
           '<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="7"/></w:numPr></w:pPr></w:style>'
           '<w:style w:type="paragraph" w:styleId="NumberedParagraph"><w:name w:val="NumberedParagraph"/>'
           '<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="8"/></w:numPr></w:pPr></w:style></w:styles>')
    bullet_p = ('<w:p w14:paraId="AAAA"><w:pPr><w:pStyle w:val="ListBullet"/>'
                '<w:numPr><w:numId w:val="0"/></w:numPr></w:pPr><w:r><w:t>Carioca MV30</w:t></w:r></w:p>')
    num_p = ('<w:p w14:paraId="BBBB"><w:pPr><w:pStyle w:val="NumberedParagraph"/>'
             '<w:numPr><w:numId w:val="0"/></w:numPr></w:pPr><w:r><w:t>continuation line</w:t></w:r></w:p>')
    c = Conformer.__new__(Conformer)
    c.num = num; c.styles = sty; c.items = [bullet_p, num_p]; c.b0 = 0
    c.disposition = 'preserve'; c.say = lambda *a, **k: None; c._bullet_restored = {}
    assert NumberingGraph(num, sty).resolve_paragraph('0', None, 'ListBullet').state == 'none'   # suppressed
    c._restore_suppressed_bullets()
    assert 'w:numId w:val="0"' not in c.items[0], 'bullet suppression not removed'
    assert 'w:numId w:val="0"' in c.items[1], 'a numbered-style continuation must be left untouched'
    assert c._bullet_restored.get('AAAA') == 'ListBullet'
    g = NumberingGraph(num, sty)
    assert g.resolve_paragraph(None, None, 'ListBullet').resolved       # now renders the house bullet
