"""Round-5 acceptance reproductions for GitHub issue #1 (A-E prescription). Independent expected results
(hand-specified, NOT generated by the code under test). Each must FAIL on the pre-fix code and PASS after.
Gates are not weakened; unresolved is never treated as conformant."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'synthetic'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"'
TEMPLATE = os.path.join(os.path.dirname(__file__), '..', 'src', 'conformer', 'assets', 'template.dotx')


# =================================================================== A. NumberingGraph resolution
def test_a_heading_selects_linked_level_not_ilvl0():
    # Heading2's style numPr carries ONLY numId 1 (no ilvl). Instance 1 -> abstract 20, whose level 1 is
    # pStyle-linked to Heading2. Correct resolution selects instance 1 and the ASSOCIATED level 1 -> (1,1),
    # decimal '%1.%2'. The old explicit-numId early return yields (1,0) which does not resolve.
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="20">'
           '<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1"/></w:lvl>'
           '<w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1.%2"/>'
           '<w:pStyle w:val="Heading2"/></w:lvl></w:abstractNum>'
           '<w:num w:numId="1"><w:abstractNumId w:val="20"/></w:num></w:numbering>')
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/>'
           '<w:pPr><w:numPr><w:numId w:val="1"/></w:numPr></w:pPr></w:style></w:styles>')
    g = NumberingGraph(num, sty)
    r = g.resolve_style('Heading2')
    assert r.state == 'resolved', r.reason
    assert (r.numId, r.ilvl) == ('1', '1'), (r.numId, r.ilvl)
    assert r.level['lvlText'] == '%1.%2'


def _two_instance_pkg(reverse=False):
    a = ('<w:abstractNum w:abstractNumId="20"><w:lvl w:ilvl="0"><w:start w:val="1"/>'
         '<w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:pStyle w:val="H"/></w:lvl></w:abstractNum>')
    n1 = '<w:num w:numId="1"><w:abstractNumId w:val="20"/></w:num>'
    n9 = ('<w:num w:numId="9"><w:abstractNumId w:val="20"/>'
          '<w:lvlOverride w:ilvl="0"><w:startOverride w:val="9"/></w:lvlOverride></w:num>')
    nums = (n9 + n1) if reverse else (n1 + n9)
    num = f'<w:numbering {W}>{a}{nums}</w:numbering>'
    sty = f'<w:styles {W}><w:style w:type="paragraph" w:styleId="H"><w:name w:val="H"/></w:style></w:styles>'
    return num, sty


def test_a_ambiguous_instance_is_unresolved():
    # Style H has no numPr; abstract 20 is pStyle-linked to H; TWO instances (num 1 start 1, num 9 start 9)
    # reference abstract 20. There is no basis to pick one -> UNRESOLVED, never a silent first-instance win.
    from conformer.numbering import NumberingGraph
    num, sty = _two_instance_pkg(reverse=False)
    g = NumberingGraph(num, sty)
    r = g.resolve_style('H')
    assert r.state == 'unresolved', (r.state, r.numId, r.ilvl)


def test_a_definition_order_independent():
    # Reversing the XML order of the two instances must NOT change the result (both unresolved here).
    from conformer.numbering import NumberingGraph
    r1 = NumberingGraph(*_two_instance_pkg(reverse=False)).resolve_style('H')
    r2 = NumberingGraph(*_two_instance_pkg(reverse=True)).resolve_style('H')
    assert r1.state == r2.state
    assert (r1.numId, r1.ilvl) == (r2.numId, r2.ilvl)


def test_a_numid0_is_no_numbering_not_unresolved():
    from conformer.numbering import NumberingGraph
    num = f'<w:numbering {W}></w:numbering>'
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="X"><w:name w:val="X"/>'
           '<w:pPr><w:numPr><w:numId w:val="0"/></w:numPr></w:pPr></w:style></w:styles>')
    r = NumberingGraph(num, sty).resolve_style('X')
    assert r.state == 'none', r.state


def test_a_missing_instance_is_unresolved_not_none():
    from conformer.numbering import NumberingGraph
    num = f'<w:numbering {W}></w:numbering>'
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="X"><w:name w:val="X"/>'
           '<w:pPr><w:numPr><w:numId w:val="77"/></w:numPr></w:pPr></w:style></w:styles>')
    r = NumberingGraph(num, sty).resolve_style('X')
    assert r.state == 'unresolved', r.state


def test_a_partial_direct_ilvl_merges_with_inherited_instance():
    # A paragraph's direct numPr has an ilvl but NO numId; the numId comes from its style. The direct ilvl
    # must NOT be discarded: resolve to (style numId, direct ilvl).
    from conformer.numbering import NumberingGraph
    num = (f'<w:numbering {W}><w:abstractNum w:abstractNumId="30">'
           '<w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl>'
           '<w:lvl w:ilvl="1"><w:numFmt w:val="lowerLetter"/><w:lvlText w:val="%2)"/></w:lvl>'
           '</w:abstractNum><w:num w:numId="5"><w:abstractNumId w:val="30"/></w:num></w:numbering>')
    sty = (f'<w:styles {W}><w:style w:type="paragraph" w:styleId="L"><w:name w:val="L"/>'
           '<w:pPr><w:numPr><w:numId w:val="5"/></w:numPr></w:pPr></w:style></w:styles>')
    g = NumberingGraph(num, sty)
    r = g.resolve_paragraph(None, '1', 'L')          # direct ilvl 1, no direct numId
    assert r.state == 'resolved' and (r.numId, r.ilvl) == ('5', '1'), (r.state, r.numId, r.ilvl)
    assert r.level['numFmt'] == 'lowerLetter'
